// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "MoveMeters.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

MoveMeters::MoveMeters(double meters): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drivetrain.get());
	Requires(Robot::gyroSubsystem.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	metersToMove = meters;
	i = 0;
}// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR


// Called just before this Command runs the first time
void MoveMeters::Initialize() {
	Robot::drivetrain->resetEncoders();
	Robot::drivetrain->driveMeters(metersToMove);
	//Robot::drivetrain->SetBrakeMode(true);

	SetTimeout(30);

	//SetTimeout(metersToMove*1.25);
}

// Called repeatedly when this Command is scheduled to run
void MoveMeters::Execute() {
	SmartDashboard::PutString("DB/String 9",std::to_string(RobotMap::drivetrainLB->GetSensorCollection().GetQuadratureVelocity()));
	i++;
}

// Make this return true when this Command no longer needs to run execute()
bool MoveMeters::IsFinished() {
	return Robot::drivetrain->AtSetpoint() || IsTimedOut();

}

// Called once after isFinished returns true
void MoveMeters::End() {
	//Robot::drivetrain->setSpeed(0,0,0,0);
	Robot::drivetrain->SetBrakeMode(false);
	Robot::drivetrain->Disable();
	Robot::gyroSubsystem->Disable();

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void MoveMeters::Interrupted() {
	//Robot::drivetrain->SetBrakeMode(false);
	Robot::drivetrain->Disable();
	Robot::gyroSubsystem->Disable();
}
