// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AdjustGrabberHeight.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AdjustGrabberLiftHeight::AdjustGrabberLiftHeight(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());

	Requires(Robot::grabberlift.get());
}
void AdjustGrabberLiftHeight::Initialize() {
}

// Called repeatedly when this Command is scheduled to run
void AdjustGrabberLiftHeight::Execute() {
	Robot::grabberlift->AdjustHeight(Robot::oi->getGamepad()->GetRawAxis(4));
}

// Make this return true when this Command no longer needs to run execute()
bool AdjustGrabberLiftHeight::IsFinished() {
	return false;

}

// Called once after isFinished returns true
void AdjustGrabberLiftHeight::End() {
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AdjustGrabberLiftHeight::Interrupted() {
}
