// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "SetGrabberAngle.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

SetGrabberAngle::SetGrabberAngle(double angleI): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());

	Requires(Robot::grabber.get());
	angle = angleI;
}
void SetGrabberAngle::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void SetGrabberAngle::Execute() {
	Robot::grabber->SetAngle(angle);
}

// Make this return true when this Command no longer needs to run execute()
bool SetGrabberAngle::IsFinished() {
	return Robot::grabber->AtSetpoint();

}

// Called once after isFinished returns true
void SetGrabberAngle::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void SetGrabberAngle::Interrupted() {
}
