// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "SetGrabberLiftHeight.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

SetGrabberLiftHeight::SetGrabberLiftHeight(int positionForLift): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());

	Requires(Robot::grabber.get());
	position = positionForLift;
}
void SetGrabberLiftHeight::Initialize() {

	switch(position){
	case 0:
		Robot::grabberlift->SetGroundHeight();
		Robot::grabber->SetAngle(0);
		break;
	case 1:
		Robot::grabberlift->SetSwitchHeight();
		Robot::grabber->SetAngle(45);
		break;
	case 2:
		Robot::grabberlift->SetMidHeight();
		Robot::grabber->SetAngle(0);
		break;
	case 3:
		Robot::grabberlift->SetHighHeight();
		Robot::grabber->SetAngle(50);
		break;
	}
}

// Called repeatedly when this Command is scheduled to run
void SetGrabberLiftHeight::Execute() {
}

// Make this return true when this Command no longer needs to run execute()
bool SetGrabberLiftHeight::IsFinished() {
	return true;

}

// Called once after isFinished returns true
void SetGrabberLiftHeight::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void SetGrabberLiftHeight::Interrupted() {
}
