// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "TurnToCube.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

TurnToCube::TurnToCube() :frc::Command() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(Robot::chassis.get());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drivetrain.get());
	Requires(Robot::communication.get());
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

}    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void TurnToCube::Initialize() {
	SetTimeout(3);
	//Robot::drivetrain->SetBrakeMode(true);
	Robot::communication->Enable();
}

// Called repeatedly when this Command is scheduled to run
void TurnToCube::Execute() {
	Robot::drivetrain->turnToCube();


}

// Make this return true when this Command no longer needs to run execute()
bool TurnToCube::IsFinished() {
	return false;
	//return Robot::communication->AtSetpoint();
	//Robot::drivetrain->SetBrakeMode(false);

}

// Called once after isFinished returns true
void TurnToCube::End() {
	Robot::communication->Disable();
	//SmartDashboard::PutString("DB/String 9", "yeeeeet");
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TurnToCube::Interrupted() {
	SmartDashboard::PutString("DB/String 1", "dude wat");
}
