// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "GrabberTest.h"
#include "WheelTest.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

GrabberTest::GrabberTest(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. Requires(Robot::
	Requires(Robot::grabberlift.get());
	Requires(Robot::grabber.get());
	Requires(Robot::grabberintake.get());
}
void GrabberTest::Initialize() {
	Robot::grabberlift->SetHighHeight();
	Robot::grabber->SetAngle(30);
}

// Called repeatedly when tahis Command is scheduled to run
void GrabberTest::Execute() {
	//Robot::grabber->SetWheelSpeed(1);
	//Robot::grabber->SetAngle(55);
}

// Make this return true when this Command no longer needs to run execute()
bool GrabberTest::IsFinished() {
	//return Robot::grabber->HasCube();
	return Robot::grabberlift->AtSetpoint();
	//return Robot::grabberlift->AtSetpoint();
}

// Called once after isFinished returns true
void GrabberTest::End() {
	//Robot::grabber->SetWheelSpeed(0);
	Robot::grabberintake->SetWheelSpeed(-1);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void GrabberTest::Interrupted() {
}
