// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ClimberTest.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ClimberTest::ClimberTest(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. Requires(Robot::
	Requires(Robot::climberlift.get());
}
void ClimberTest::Initialize() {
	Robot::climberlift->SetSpeed(0.5);
}

// Called repeatedly when tahis Command is scheduled to run
void ClimberTest::Execute() {
	//Robot::grabber->SetWheelSpeed(1);
	//Robot::grabber->SetAngle(55);
}

// Make this return true when this Command no longer needs to run execute()
bool ClimberTest::IsFinished() {
	//return Robot::grabber->HasCube();
	return Robot::climberlift->AtTopLimit();
	//return Robot::grabberlift->AtSetpoint();
}

// Called once after isFinished returns true
void ClimberTest::End() {
	SmartDashboard::PutString("DB String/1", "AAAAA");
	Robot::climberlift->SetSpeed(0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ClimberTest::Interrupted() {
}
