// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "WheelTest.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

WheelTest::WheelTest(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. Requires(Robot::
	Requires(Robot::drivetrain.get());
}
void WheelTest::Initialize() {
	Robot::drivetrain->resetEncoders();
}

// Called repeatedly when tahis Command is scheduled to run
void WheelTest::Execute() {
	Robot::drivetrain->setSpeed(0.75,0.75,0.75,0.75);

	}

// Make this return true when this Command no longer needs to run execute()
bool WheelTest::IsFinished() {
	return false;

}

// Called once after isFinished returns true
void WheelTest::End() {
	Robot::drivetrain->setSpeed(0,0,0,0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void WheelTest::Interrupted() {
}
