// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "StopFromAccel.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

StopFromAccel::StopFromAccel(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drivetrain.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

	i = 0;
}// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR


// Called just before this Command runs the first time
void StopFromAccel::Initialize() {
	SetTimeout(4);
}

// Called repeatedly when this Command is scheduled to run
void StopFromAccel::Execute() {

	Robot::drivetrain->setSpeed(0.25,0.25,0.25,0.25);
}

// Make this return true when this Command no longer needs to run execute()
bool StopFromAccel::IsFinished() {
	return !Robot ::drivetrain->isMovingWithAccelY() || IsTimedOut();

}

// Called once after isFinished returns true
void StopFromAccel::End() {
	SmartDashboard::PutString("DB/String 9","yeeeeet");
	Robot::drivetrain->setSpeed(0,0,0,0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void StopFromAccel::Interrupted() {
	SmartDashboard::PutString("DB/String 1","int");
}
