// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "Position2L.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Position2L::Position2L() : CommandGroup("2L") {

	//Requires(Robot::grabberlift.get());
	/*AddSequential(new MoveMeters(1.5));
	AddSequential(new TurnDegrees(-90));
	AddSequential(new MoveMeters(3));
	AddSequential(new TurnDegrees(90));*/
	AddParallel(new SetGrabberAngleAuto(0));
	AddParallel(new SetGrabberLiftHeightAuto(1));
	AddSequential(new StopFromAccel());
	AddSequential(new SetIntakeWheelSpeedForTime(-1,0.4));
	AddSequential(new MoveMeters(-1));
	AddParallel(new SetGrabberLiftHeightAuto(0));
	AddSequential(new TurnDegrees(90));
	//Deploy Box
}

void Position2L::Initialize(){
		//AddSequential(new SetIntakeWheelSpeedForTime(1,0.4));
		 }
void Position2L::Execute(){
		//AddSequential(new SetIntakeWheelSpeedForTime(1,0.4));
}
bool Position2L::IsFinished(){
	return false;
		//AddSequential(new SetIntakeWheelSpeedForTime(1,0.4));
}
void Position2L::End(){
	//AddSequential(new SetIntakeWheelSpeedForTime(1,0.4));
}
void Position2L::Interrupted(){
	//AddSequential(new SetIntakeWheelSpeedForTime(1,0.4));
}

