// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "Position1LR.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Position1LR::Position1LR()  : CommandGroup("1LR") {
	AddParallel(new SetGrabberAngleAuto(0));
	AddParallel(new SetGrabberLiftHeightAuto(1));
	AddSequential(new MoveMeters(4.51));
	AddSequential(new TurnDegrees(90));
	AddSequential(new StopFromAccel());
	AddSequential(new SetIntakeWheelSpeedForTime(-1,0.3));
	AddSequential(new MoveMeters(-1));
	AddParallel(new SetGrabberLiftHeightAuto(0));
	AddSequential(new TurnDegrees(-90));



/*
	AddSequential(new MoveMeters(4.51));
	AddSequential(new TurnDegrees(90));
	AddSequential(new StopFromAccel());

	//insert wheel spin thing
	AddSequential(new MoveMeters(-.61));

	//Using turning
	AddSequential(new TurnDegrees(-90));
	AddSequential(new MoveMeters(.61));
	AddSequential(new TurnDegrees(90));
	//insert wheel spin thing
	AddSequential(new TurnDegrees(-90));
	AddSequential(new MoveMeters(.61));
	AddSequential(new TurnDegrees(90));
	*/
	//Using Strafing
	/*AddSequential(new StrafeRotations(6));
	//insert wheel spin thing
	AddSequential(new StrafeRotations(6));*/

	//AddSequential(new MoveMeters(3.29));

 }
