// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#ifndef POSITION2LTHEREALTHOUGH_H
#define POSITION2LTHEREALTHOUGH_H

#include "Commands/CommandGroup.h"
#include "../MoveMeters.h"
#include "../StopFromAccel.h"
#include "../TurnDegrees.h"
#include "../SetIntakeWheelSpeedForTime.h"
#include "../SetGrabberLiftHeightAuto.h"
#include "../SetGrabberAngleAuto.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class Position2L: public frc::CommandGroup{
public:

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	Position2L();
	void Initialize() override;
	void Execute() override;
	bool IsFinished() override;
	void End() override;
	void Interrupted() override;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

private:

};

#endif
