// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#ifndef POSITION1RL_H
#define POSITION1RL_H


#include "Commands/CommandGroup.h"
#include "../MoveMeters.h"
#include "../StopFromAccel.h"
#include "../TurnDegrees.h"
#include "../StrafeRotations.h"
#include "../SetIntakeWheelSpeedForTime.h"
#include "../SetGrabberAngleAuto.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Position1RL: public frc::CommandGroup {
public:

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	Position1RL();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

private:

};

#endif
