// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "Position3RL.h"
#include "../../SetGrabberLiftHeight.h"
#include "../../SetIntakeWheelSpeed.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Position3RL::Position3RL() : CommandGroup("3RL")  {
	//scale
	AddSequential(new MoveMeters(8.44));
	AddSequential(new TurnDegrees(90));
	AddSequential(new StopFromAccel());
	AddSequential(new MoveMeters(0));
	AddSequential(new SetGrabberLiftHeight(2));
	AddSequential(new SetIntakeWheelSpeed(-0.2));
	//wait(1);
	AddSequential(new SetIntakeWheelSpeed(0));
	AddSequential(new SetGrabberLiftHeight(0));
	AddSequential(new MoveMeters(0));
	AddSequential(new TurnDegrees(90));
	//cube
	AddSequential(new MoveMeters(0));
	AddSequential(new SetIntakeWheelSpeed(0.2));
		//vision magic
	AddSequential(new SetIntakeWheelSpeed(0));
		//displacement
	//switch
	AddSequential(new SetGrabberLiftHeight(1));
	AddSequential(new SetIntakeWheelSpeed(-0.2));
	AddSequential(new SetIntakeWheelSpeed(0));
 }

