// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "Position1LL.h"


// BEGIN AUTOGENERATED CODE, SOURCE=RO BOTBUILDER ID=CONSTRUCTOR

Position1LL::Position1LL()  : CommandGroup("1LL") {
	//scale
	AddSequential(new MoveMeters(8.44));
	AddSequential(new TurnDegrees(90));
	AddParallel(new MoveMeters(-1));
	AddSequential(new SetGrabberLiftHeightAuto(3));
	AddSequential(new MoveMeters(1));
	AddSequential(new SetIntakeWheelSpeedForTime(-1,0.4));
	AddSequential(new MoveMeters(-1));
	AddParallel(new SetGrabberLiftHeightAuto(0));

	AddSequential(new TurnDegrees(90));

 }
