// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "ctre/Phoenix.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<WPI_TalonSRX> RobotMap::drivetrainRF;
std::shared_ptr<WPI_TalonSRX> RobotMap::drivetrainRB;
std::shared_ptr<WPI_TalonSRX> RobotMap::drivetrainLF;
std::shared_ptr<WPI_TalonSRX> RobotMap::drivetrainLB;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

std::shared_ptr<frc::AnalogGyro> RobotMap::sensorsAnalogGyro1;
std::shared_ptr<frc::ADXL345_I2C> RobotMap::accel;
void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    //frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    drivetrainRF.reset(new WPI_TalonSRX(1));
    
    
    drivetrainRB.reset(new WPI_TalonSRX(2));
    
    
    drivetrainLF.reset(new WPI_TalonSRX(3));
    
    
    drivetrainLB.reset(new WPI_TalonSRX(4));
    sensorsAnalogGyro1.reset(new frc::AnalogGyro(0));
    sensorsAnalogGyro1->SetSensitivity(0.007);
    
    accel.reset(new frc::ADXL345_I2C(I2C::Port::kOnboard,Accelerometer::Range::kRange_4G));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
