// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef CLAWLIFT_H
#define CLAWLIFT_H
#include "Commands/Subsystem.h"
#include "WPILib.h"


/**
 *
 *
 * @author ExampleAuthor
 */
class ClawLift: public frc::PIDSubsystem{
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<WPI_TalonSRX> liftTalon;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	ClawLift();
	void InitDefaultCommand() override;
	void Periodic() override;
	double ReturnPIDInput() override;
	void UsePIDOutput(double output) override;
	bool AtSetpoint();
	void SetGroundHeight();
	void SetSwitchHeight();
	void SetMidHeight();
	void SetHighHeight();
	void AdjustHeight(double modifier);
	void ResetEncoders();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
