#include "ctre/Phoenix.h"
#include "Grabber.h"
#include "../RobotMap.h"
#include "../Commands/AdjustGrabberAngle.h"
Grabber::Grabber() : frc::PIDSubsystem("ClawLift",0.075,0,0.06) {//Change PID Values

    SetAbsoluteTolerance(0.01);
    GetPIDController()->SetContinuous(false);
    armL = RobotMap::grabberactuatorL;
    armR = RobotMap::grabberactuatorR;
	SetOutputRange(-0.75,0.75);//Change these values to change speed

	armR->Set(ctre::phoenix::motorcontrol::ControlMode::Follower,8);

	//armR->SetInverted(true);//change to armL if arms aren't turning the right way
	//wheelR->SetInverted(true);//change to wheelL if wheels aren't turning the right way


    ultrasonic = RobotMap::sensorsUltrasonic;
    inclinometerX = RobotMap::sensorsInclinometerX;
    inclinometerY = RobotMap::sensorsInclinometerY;
    upperSwitch = RobotMap::grabberswitchupper;
    lowerSwitch = RobotMap::grabberswitchlower;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    range = 0;
    angle = 0;
    minPosition = -15;
    maxPosition = 49.99;
    isEnabled=true;


	//angleY = 0;
    //Enable();
}

void Grabber::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    SetDefaultCommand(new AdjustGrabberAngle(0));
}

void Grabber::Periodic() {
	SmartDashboard::PutString("DB/String 8",std::to_string(InclinometerAngle()));

	if(upperSwitch->Get() && InclinometerAngle()>20){
		maxPosition=InclinometerAngle();
		if(GetSetpoint()>maxPosition){
			SetSetpoint(maxPosition);
		}
		//SmartDashboard::PutString("DB/String 9",std::to_string(maxPosition));

	}
	else if(lowerSwitch->Get()&& InclinometerAngle()<20){
		minPosition = InclinometerAngle();

		if(GetSetpoint()<minPosition){
			SetSetpoint(minPosition);
		}
	}


}

double Grabber::ReturnPIDInput() {
	return InclinometerAngle();
}
void Grabber::UsePIDOutput(double output) {
	armL->Set(output);
}

bool Grabber::AtSetpoint(){
	return -3>GetSetpoint()-InclinometerAngle() && 3>GetSetpoint()-InclinometerAngle();
}
void Grabber::SetAngle(double angle){
	if(angle>=minPosition && angle<=maxPosition){
		SetSetpoint(angle);
	}
}
void Grabber::AdjustAngle(double speed){
	armL->Set(speed);
	if(!(DeadBand(speed,0.15)==0)){
		Disable();
		if(upperSwitch->Get() && speed<0){
			armL->Set(speed);
		}
		else if (lowerSwitch->Get() && speed>0){
			armL->Set(speed);
		}
		else if (!lowerSwitch->Get() && !upperSwitch->Get()){
			armL->Set(speed);
		}
		else{
			armL->Set(0);
		}
		isEnabled = false;
	}
	else{
		armL->Set(0);
		if(!isEnabled){
			SetSetpoint(InclinometerAngle());
			isEnabled = true;
			//Enable();
		}
	}

}
double Grabber::DeadBand(double input, double band){
	if(input > band || input <-band){
		return input;
	}
	else{
		return 0;
	}
}

double Grabber::Ultrasonic() {
	int bits;
	ultrasonic->SetAverageBits(4);
	bits = ultrasonic->GetAverageBits();
	double averageVoltage = ultrasonic->GetAverageVoltage();
	range = averageVoltage / 0.00024892;
	//range given in meters
	return range;
}
double Grabber::InclinometerAngle() {
	//int bits;
	//inclinometerX->SetOversampleBits(2);
	//bits = inclinometerX->GetOversampleBits();
	//double averageVoltage = inclinometerX->GetAverageVoltage();
	double Voltage = inclinometerX->GetVoltage();
	angle = (Voltage - 2.5) * 45;
	//angle given in degrees
	return angle;
}

/*double Grabber::InclinometerY() {
	int bits;
	inclinometerY->SetAverageBits(4);
	bits = inclinometerY->GetAverageBits();
	double averageVoltage = inclinometerY->GetAverageVoltage();
	angleY = (averageVoltage - 2.5) * 45;
	//angleY given in degrees
	return angleY;
}*/
