// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef CLAW_H
#define CLAW_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class GyroSubsystem: public frc::PIDSubsystem {
private:
	double ReturnPIDInput();//Internal Function Only!
	void UsePIDOutput(double output);//Internal Function Only!
public:
	GyroSubsystem();
	void InitDefaultCommand() override;
		void Periodic() override;
		double gAngle();//returns angle from gyro
		double getGyroRate();//returns rate of change of the angle
		void setDegrees(double degrees);//Set PID loop to go to degrees
		void setZero();

		bool AtSetpoint();//returns true if the angle is close enough to target
		void strafeRight();
		void strafeLeft();
		double modifier = 0;
		bool turningOnly = false;
		double GetModifier();//return PID output to turn Robot
		void ResetGyro();//Reset Gyro back to 0 degreess


	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
