// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/JoystickDrivetrain.h"
#include "Commands/AutonomousCommands/MoveMeters.h"
#include "Commands/SetGrabberLiftHeight.h"
#include "Commands/AdjustGrabberAngle.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	gamepad.reset(new frc::Joystick(2));
    joystick2.reset(new frc::Joystick(1));
    
    joystick1.reset(new frc::Joystick(0));
    

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("Joystick Drivetrain", new JoystickDrivetrain());
    //frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS


	XButton.reset(new frc::JoystickButton(gamepad.get(), 1));
			AButton.reset(new JoystickButton(gamepad.get(), 2));
			BButton.reset(new JoystickButton(gamepad.get(), 3));
			YButton.reset(new JoystickButton(gamepad.get(), 4));
			LFButton.reset(new JoystickButton(gamepad.get(), 5));
			RFButton.reset(new JoystickButton(gamepad.get(), 6));
			LBButton.reset(new JoystickButton(gamepad.get(), 7));
			RBButton.reset(new JoystickButton(gamepad.get(), 8));

	XButton->WhenPressed(new SetGrabberLiftHeight(0));
	AButton->WhenPressed(new SetGrabberLiftHeight(1));
	BButton->WhenPressed(new SetGrabberLiftHeight(2));
	YButton->WhenPressed(new SetGrabberLiftHeight(3));

	RBButton->WhileHeld(new AdjustGrabberAngle(-0.5));
	RFButton->WhileHeld(new AdjustGrabberAngle(0.5));

}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getGamepad() {
   return gamepad;
}
std::shared_ptr<frc::Joystick> OI::getJoystick1() {
   return joystick1;
}

std::shared_ptr<frc::Joystick> OI::getJoystick2() {
   return joystick2;
}


// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
